(* `fennec gen-doctests <dir>` — generate an OCaml module that runs the executable doc examples
   ({@ocaml[ … ]} blocks) from the .mli INTERFACES in <dir> as tests. Wired by a one-time dune
   (rule) — the route_gen pattern — so an example in a public interface both RENDERS in odoc AND
   executes (cannot drift), without a ppx (dune sandboxes the preprocess, so a ppx can't read the
   sibling .mli) and without any per-example userland artifact.

   The generated module joins the SAME library (via [(modules :standard)]), so each [foo.mli]'s
   example runs with [open Foo] in scope — the public values it documents resolve by their bare
   names. The whole thing is pure (extraction + text generation); the CLI just prints it. *)

open Ppxlib

(* ── {@ocaml[ … ]} block extraction (same convention as the ppx; skips [skip]-labelled), each with
   its 1-based source line ── *)
let str_contains hay needle =
  let hn = String.length hay and nn = String.length needle in
  if nn = 0 then true
  else
    let rec go i = if i + nn > hn then false else if String.sub hay i nn = needle then true else go (i + 1) in
    go 0

let code_blocks_located (doc : string) : (string * int) list =
  let n = String.length doc in
  let find sub start =
    let sl = String.length sub in
    let rec go j = if j + sl > n then -1 else if String.sub doc j sl = sub then j else go (j + 1) in
    go start
  in
  let line_at pos = let c = ref 1 in for j = 0 to min pos n - 1 do if doc.[j] = '\n' then incr c done; !c in
  let blocks = ref [] and i = ref 0 and go = ref true in
  while !go do
    let tag = find "{@ocaml" !i in
    if tag < 0 then go := false
    else
      let lb = find "[" (tag + 7) in
      let rb = if lb < 0 then -1 else find "]}" (lb + 1) in
      if lb < 0 || rb < 0 then go := false
      else begin
        let labels = String.sub doc (tag + 7) (lb - (tag + 7)) in
        if not (str_contains labels "skip") then blocks := (String.sub doc (lb + 1) (rb - lb - 1), line_at tag) :: !blocks;
        i := rb + 2
      end
  done;
  List.rev !blocks

(* a single bare expression (e.g. [assert (add 2 3 = 5)]) runs as [ignore (…)] so any result type
   is fine; anything with top-level bindings runs as a local module's body *)
let classify code =
  match (try Parse.implementation (Lexing.from_string code) with _ -> []) with
  | [ { pstr_desc = Pstr_eval _; _ } ] -> `Expr
  | _ -> `Struct

(* foo.mli → Foo, products/id_.mli → Id_ *)
let module_of_mli mli = String.capitalize_ascii (Filename.remove_extension (Filename.basename mli))

let generate ~dir : string =
  let mlis =
    match Sys.readdir dir with
    | exception _ -> []
    | a ->
      Array.to_list a
      (* real interfaces only — skip dune's preprocessed copies (foo.pp.mli) that sit in _build *)
      |> List.filter (fun f -> Filename.check_suffix f ".mli" && not (str_contains f ".pp."))
      |> List.sort compare
  in
  let buf = Buffer.create 1024 in
  Buffer.add_string buf
    "(* GENERATED by `fennec gen-doctests` — do not edit. Runs the {@ocaml[ … ]} doc examples from\n   the .mli interfaces in this directory as tests (they also render in odoc). *)\n\n";
  List.iter
    (fun mli ->
      let text = match In_channel.with_open_bin (Filename.concat dir mli) In_channel.input_all with s -> s | exception _ -> "" in
      match code_blocks_located text with
      | [] -> ()
      | blocks ->
        let m = module_of_mli mli in
        List.iter
          (fun (code, line) ->
            let wrapped =
              match classify code with
              | `Expr -> Printf.sprintf "ignore (\n%s\n)" code
              | `Struct -> Printf.sprintf "let module _ = struct\n%s\nend in ()" code
            in
            Buffer.add_string buf
              (Printf.sprintf "let () = Fennec_hunt_unit.test_unit_loc ~name:%S ~file:%S ~line:%d (fun () ->\n  let open %s in\n  %s)\n\n"
                 (Printf.sprintf "doc example (%s:%d)" mli line) mli line m wrapped))
          blocks)
    mlis;
  Buffer.contents buf
