(* wiring_gen — emit a workflow WIRING MANIFEST. A `[@cron]` / `[@every]` / `[@after]` annotation
   registers its job/reaction at the module's init, but a module is only linked (and so only inits) if
   something references it. A PURE-cron workflow that nothing calls would therefore silently never run.

   This generator scans a workflows directory and emits `wiring.ml` — a module that references every
   workflow module, so linking the manifest force-links them all. The server then references ONE symbol
   ([Wiring.link]) instead of having to name each workflow by hand. Usage: wiring_gen <src-dir> <out>. *)

let () =
  let dir = Sys.argv.(1) and out = Sys.argv.(2) in
  let mods =
    Sys.readdir dir |> Array.to_list
    |> List.filter (fun f ->
           Filename.check_suffix f ".ml" && f <> "wiring.ml"
           (* a real source module is a single-segment basename — skip ppx/build artifacts like
              tickets.pp.ml (their chopped name still contains a '.') *)
           && not (String.contains (Filename.chop_suffix f ".ml") '.'))
    |> List.map (fun f -> String.capitalize_ascii (Filename.chop_suffix f ".ml"))
    |> List.sort_uniq compare
  in
  let b = Buffer.create 256 in
  Buffer.add_string b
    "(* GENERATED by fennec — do not edit. References every workflow module so its [@cron] / [@every] /\n\
    \   [@after] annotations register at boot even when nothing else links it. Reference [Wiring.link]\n\
    \   once from the server (e.g. `let () = Wiring.link ()`) to force-link them all. *)\n";
  (* a named empty module type — an inline [sig end] is not a valid first-class-module package type *)
  Buffer.add_string b "module type _Link = sig end\n";
  Buffer.add_string b "let link () =\n";
  (* packing each module as a first-class value references it, so the linker keeps it and it inits *)
  List.iter (fun m -> Buffer.add_string b (Printf.sprintf "  ignore (module %s : _Link);\n" m)) mods;
  Buffer.add_string b "  ()\n";
  let oc = open_out out in
  output_string oc (Buffer.contents b);
  close_out oc
