(* `fennec embed` — walk a directory (e.g. public/) and emit an OCaml module that
   maps each relative file path to its bytes, for compile-time embedding into the
   binary. In prod the server serves these from memory (single self-contained
   executable); in dev it reads the directory directly. The generated module
   exposes:

     val lookup : string -> string option   (* path key -> bytes *)
     val paths  : string list

   Driven by a dune rule, exactly like `fennec build` — same CLI-as-build-tool
   pattern. The bytes are emitted as OCaml string literals (escaped), which the
   compiler stores verbatim; no base64 bloat. *)

let pf = Printf.printf
let ef = Printf.eprintf

(* recursively list files under [root], returning paths RELATIVE to root, with
   '/' separators, sorted for deterministic output *)
let list_files root =
  let acc = ref [] in
  let rec walk rel =
    let abs = if rel = "" then root else Filename.concat root rel in
    let entries = try Sys.readdir abs with _ -> [||] in
    Array.sort compare entries;
    Array.iter
      (fun name ->
        let rel' = if rel = "" then name else rel ^ "/" ^ name in
        let abs' = Filename.concat abs name in
        if (try Sys.is_directory abs' with _ -> false) then walk rel'
        else acc := rel' :: !acc)
      entries
  in
  walk "";
  List.sort compare (List.rev !acc)

let read_file path = In_channel.with_open_bin path In_channel.input_all

(* emit an OCaml string literal for arbitrary bytes: escape so the compiler
   reproduces the exact bytes. Use \xNN for non-printable / non-ASCII and the
   quote/backslash specials. *)
let ocaml_string_literal (s : string) : string =
  let b = Buffer.create (String.length s + 16) in
  Buffer.add_char b '"';
  String.iter
    (fun c ->
      let code = Char.code c in
      match c with
      | '"' -> Buffer.add_string b "\\\""
      | '\\' -> Buffer.add_string b "\\\\"
      | '\n' -> Buffer.add_string b "\\n"
      | '\t' -> Buffer.add_string b "\\t"
      | '\r' -> Buffer.add_string b "\\r"
      | _ when code >= 32 && code < 127 -> Buffer.add_char b c
      | _ -> Buffer.add_string b (Printf.sprintf "\\x%02x" code))
    s;
  Buffer.add_char b '"';
  Buffer.contents b

let run dir out =
  if not (Sys.file_exists dir && Sys.is_directory dir) then begin
    ef "fennec embed: %s is not a directory\n" dir;
    1
  end
  else begin
    let files = list_files dir in
    let oc = open_out out in
    let p fmt = Printf.fprintf oc fmt in
    p "(* generated by `fennec embed %s` — do not edit *)\n" dir;
    p "let assets : (string * string) list = [\n";
    List.iter
      (fun rel ->
        let bytes = read_file (Filename.concat dir rel) in
        p "  (%s, %s);\n" (ocaml_string_literal rel) (ocaml_string_literal bytes))
      files;
    p "]\n\n";
    p "let table = lazy (let h = Hashtbl.create (List.length assets) in\n";
    p "  List.iter (fun (k, v) -> Hashtbl.replace h k v) assets; h)\n\n";
    p "let lookup (path : string) : string option =\n";
    p "  Hashtbl.find_opt (Lazy.force table) path\n\n";
    p "let paths : string list = List.map fst assets\n";
    close_out oc;
    pf "  embedded %d file(s) from %s -> %s\n" (List.length files) dir out;
    flush stdout;
    0
  end
