(* Web-root assembly helpers used by `fennec build`:
     - stage a public/ tree into the output dir (paths preserved), erroring on any
       clash with a file already there (i.e. a bundle output)
     - emit the prod embed module (path -> bytes) from the assembled output dir

   There is no `assemble`/`embed` subcommand: these are driven by the --public and
   --embed flags on `build`, so the web root is just the build output dir with the
   public tree merged in. *)

let ef = Printf.eprintf

(* list files under [root] relative to it, '/'-separated, sorted *)
let list_files root =
  let acc = ref [] in
  let rec walk rel =
    let abs = if rel = "" then root else Filename.concat root rel in
    let entries = try Sys.readdir abs with _ -> [||] in
    Array.sort compare entries;
    Array.iter
      (fun name ->
        let rel' = if rel = "" then name else rel ^ "/" ^ name in
        if (try Sys.is_directory (Filename.concat abs name) with _ -> false) then walk rel'
        else acc := rel' :: !acc)
      entries
  in
  walk "";
  List.sort compare (List.rev !acc)

let read_file path = In_channel.with_open_bin path In_channel.input_all

let write_file path contents =
  Out_channel.with_open_bin path (fun oc -> Out_channel.output_string oc contents)

let rec mkdir_p dir =
  if dir = "" || dir = "." || dir = "/" || Sys.file_exists dir then ()
  else begin
    mkdir_p (Filename.dirname dir);
    (try Unix.mkdir dir 0o755 with Unix.Unix_error (Unix.EEXIST, _, _) -> ())
  end

(* Copy a pre-built file [src] into [outdir] at its basename (a bundle built by a
   sibling dune rule). A clash with a file already in [outdir] is a hard error. *)
let include_file ~outdir ~src : (unit, string) result =
  if not (Sys.file_exists src) then Error (Printf.sprintf "--include: %s not found" src)
  else
    let dst = Filename.concat outdir (Filename.basename src) in
    if Sys.file_exists dst then
      Error
        (Printf.sprintf "clash: included file %S collides with another web-root file at the same path"
           (Filename.basename src))
    else begin
      mkdir_p (Filename.dirname dst);
      write_file dst (read_file src);
      Ok ()
    end

(* Stage [public_dir]'s tree into [outdir]. A clash with a file ALREADY in
   [outdir] (a bundle output) is a hard error naming both sides. Returns Ok () or
   Error message. *)
let stage_public ~outdir ~public_dir : (unit, string) result =
  if not (Sys.file_exists public_dir && Sys.is_directory public_dir) then
    Error (Printf.sprintf "--public: %s is not a directory" public_dir)
  else
    let rec check = function
      | [] -> Ok ()
      | rel :: rest ->
        let dst = Filename.concat outdir rel in
        if Sys.file_exists dst then
          Error
            (Printf.sprintf "clash: public file %S collides with a build output at the same path"
               rel)
        else check rest
    in
    let files = list_files public_dir in
    match check files with
    | Error _ as e -> e
    | Ok () ->
      List.iter
        (fun rel ->
          let dst = Filename.concat outdir rel in
          mkdir_p (Filename.dirname dst);
          write_file dst (read_file (Filename.concat public_dir rel)))
        files;
      Ok ()

(* emit an OCaml string literal preserving exact bytes *)
let ocaml_string_literal (s : string) : string =
  let b = Buffer.create (String.length s + 16) in
  Buffer.add_char b '"';
  String.iter
    (fun c ->
      let code = Char.code c in
      match c with
      | '"' -> Buffer.add_string b "\\\""
      | '\\' -> Buffer.add_string b "\\\\"
      | '\n' -> Buffer.add_string b "\\n"
      | '\t' -> Buffer.add_string b "\\t"
      | '\r' -> Buffer.add_string b "\\r"
      | _ when code >= 32 && code < 127 -> Buffer.add_char b c
      | _ -> Buffer.add_string b (Printf.sprintf "\\x%02x" code))
    s;
  Buffer.add_char b '"';
  Buffer.contents b

(* Emit [out_file]: an OCaml module mapping each file under [outdir] (the
   assembled web root) to its bytes, for compile-time embedding. *)
let emit_embed ~outdir ~out_file : (int, string) result =
  if not (Sys.file_exists outdir && Sys.is_directory outdir) then
    Error (Printf.sprintf "--embed: %s is not a directory" outdir)
  else begin
    let files = list_files outdir |> List.filter (fun f -> f <> Filename.basename out_file) in
    let oc = open_out out_file in
    let p fmt = Printf.fprintf oc fmt in
    p "(* generated by `fennec build --embed` — do not edit *)\n";
    p "let assets : (string * string) list = [\n";
    List.iter
      (fun rel ->
        p "  (%s, %s);\n" (ocaml_string_literal rel)
          (ocaml_string_literal (read_file (Filename.concat outdir rel))))
      files;
    p "]\n\n";
    p "let table = lazy (let h = Hashtbl.create (List.length assets) in\n";
    p "  List.iter (fun (k, v) -> Hashtbl.replace h k v) assets; h)\n\n";
    p "let lookup (path : string) : string option = Hashtbl.find_opt (Lazy.force table) path\n\n";
    p "let paths : string list = List.map fst assets\n";
    close_out oc;
    Ok (List.length files)
  end

let warn_clash msg = ef "fennec build: %s\n" msg
