(* Web-root assembly helpers used by `fennec build`:
     - stage a public/ tree into the output dir (paths preserved), erroring on any
       clash with a file already there (i.e. a bundle output)
     - emit the prod embed module (path -> bytes) from the assembled output dir

   There is no `assemble`/`embed` subcommand: these are driven by the --public and
   --embed flags on `build`, so the web root is just the build output dir with the
   public tree merged in. *)

let ef = Printf.eprintf

(* list files under [root] relative to it, '/'-separated, sorted *)
let list_files root =
  let acc = ref [] in
  let rec walk rel =
    let abs = if rel = "" then root else Filename.concat root rel in
    let entries = try Sys.readdir abs with _ -> [||] in
    Array.sort compare entries;
    Array.iter
      (fun name ->
        let rel' = if rel = "" then name else rel ^ "/" ^ name in
        if (try Sys.is_directory (Filename.concat abs name) with _ -> false) then walk rel'
        else acc := rel' :: !acc)
      entries
  in
  walk "";
  List.sort compare (List.rev !acc)

let read_file path = In_channel.with_open_bin path In_channel.input_all

let write_file path contents =
  Out_channel.with_open_bin path (fun oc -> Out_channel.output_string oc contents)

let rec mkdir_p dir =
  if dir = "" || dir = "." || dir = "/" || Sys.file_exists dir then ()
  else begin
    mkdir_p (Filename.dirname dir);
    (try Unix.mkdir dir 0o755 with Unix.Unix_error (Unix.EEXIST, _, _) -> ())
  end

(* Copy a pre-built file into [outdir] (a bundle built by a sibling dune rule).
   [spec] is either "path" (kept at its basename) or "path:dest" (placed at
   [dest], e.g. "web.js:app.js"). A clash with a file already in [outdir] is a
   hard error. *)
let include_file ~outdir ~spec : (unit, string) result =
  let src, dest =
    match String.index_opt spec ':' with
    | Some i -> (String.sub spec 0 i, String.sub spec (i + 1) (String.length spec - i - 1))
    | None -> (spec, Filename.basename spec)
  in
  if not (Sys.file_exists src) then Error (Printf.sprintf "--include: %s not found" src)
  else
    let dst = Filename.concat outdir dest in
    if Sys.file_exists dst then
      Error
        (Printf.sprintf "clash: included file %S collides with another web-root file at the same path"
           dest)
    else begin
      mkdir_p (Filename.dirname dst);
      write_file dst (read_file src);
      Ok ()
    end

(* Stage [public_dir]'s tree into [outdir]. A clash with a file ALREADY in
   [outdir] (a bundle output) is a hard error naming both sides. Returns Ok () or
   Error message. *)
let stage_public ~outdir ~public_dir : (unit, string) result =
  if not (Sys.file_exists public_dir && Sys.is_directory public_dir) then
    Error (Printf.sprintf "--public: %s is not a directory" public_dir)
  else
    let rec check = function
      | [] -> Ok ()
      | rel :: rest ->
        let dst = Filename.concat outdir rel in
        if Sys.file_exists dst then
          Error
            (Printf.sprintf "clash: public file %S collides with a build output at the same path"
               rel)
        else check rest
    in
    let files = list_files public_dir in
    match check files with
    | Error _ as e -> e
    | Ok () ->
      List.iter
        (fun rel ->
          let dst = Filename.concat outdir rel in
          mkdir_p (Filename.dirname dst);
          write_file dst (read_file (Filename.concat public_dir rel)))
        files;
      Ok ()

(* emit an OCaml string literal preserving exact bytes *)
let ocaml_string_literal (s : string) : string =
  let b = Buffer.create (String.length s + 16) in
  Buffer.add_char b '"';
  String.iter
    (fun c ->
      let code = Char.code c in
      match c with
      | '"' -> Buffer.add_string b "\\\""
      | '\\' -> Buffer.add_string b "\\\\"
      | '\n' -> Buffer.add_string b "\\n"
      | '\t' -> Buffer.add_string b "\\t"
      | '\r' -> Buffer.add_string b "\\r"
      | _ when code >= 32 && code < 127 -> Buffer.add_char b c
      | _ -> Buffer.add_string b (Printf.sprintf "\\x%02x" code))
    s;
  Buffer.add_char b '"';
  Buffer.contents b

(* Emit [out_file]: an OCaml module mapping each file under [outdir] (the
   assembled web root) to its bytes, for compile-time embedding. *)
let emit_embed ~outdir ~out_file : (int, string) result =
  if not (Sys.file_exists outdir && Sys.is_directory outdir) then
    Error (Printf.sprintf "--embed: %s is not a directory" outdir)
  else begin
    let files = list_files outdir |> List.filter (fun f -> f <> Filename.basename out_file) in
    let oc = open_out out_file in
    let p fmt = Printf.fprintf oc fmt in
    p "(* generated by `fennec build --embed` — do not edit *)\n";
    p "let assets : (string * string) list = [\n";
    List.iter
      (fun rel ->
        p "  (%s, %s);\n" (ocaml_string_literal rel)
          (ocaml_string_literal (read_file (Filename.concat outdir rel))))
      files;
    p "]\n\n";
    p "let table = lazy (let h = Hashtbl.create (List.length assets) in\n";
    p "  List.iter (fun (k, v) -> Hashtbl.replace h k v) assets; h)\n\n";
    p "let lookup (path : string) : string option = Hashtbl.find_opt (Lazy.force table) path\n\n";
    p "let paths : string list = List.map fst assets\n";
    close_out oc;
    Ok (List.length files)
  end

let warn_clash msg = ef "fennec build: %s\n" msg

(* ---- assemble: build ONE web root from a frontend/ tree ----

   The whole isomorphic frontend is one tree (apps/ components/ templates/),
   dual-compiled elsewhere by dune (native SSR lib + a melange mirror that emits
   per-app JS). This step turns those outputs into the served web root, with NO
   per-app dune wiring: it DISCOVERS the apps (folders under frontend/apps with a
   main.mlx) and, for each, esbuild-bundles its emitted JS entry and compiles its
   main.scss — into the predictable /_apps/<name>/main.{js,css}. It also builds
   the shared /react.js runtime once and merges the static public/ tree in. *)

(* recursively collect files under [root] whose path ends with [suffix] *)
let rec find_ending root suffix acc =
  let entries = try Sys.readdir root with _ -> [||] in
  Array.fold_left
    (fun acc name ->
      let p = Filename.concat root name in
      if (try Sys.is_directory p with _ -> false) then find_ending p suffix acc
      else if Filename.check_suffix p suffix then p :: acc
      else acc)
    acc entries

(* app names = subdirs of <frontend>/apps that contain a main.mlx, sorted *)
let discover_apps frontend_dir =
  let apps_dir = Filename.concat frontend_dir "apps" in
  let entries = try Sys.readdir apps_dir with _ -> [||] in
  Array.to_list entries
  |> List.filter (fun name ->
         Sys.file_exists (Filename.concat (Filename.concat apps_dir name) "main.mlx"))
  |> List.sort compare

let assemble ~emit_dir ~frontend_dir ~public_dir ~runtime ~shim ~outdir ~minify :
    (unit, string) result =
  try
    mkdir_p outdir;
    (* shared preact runtime -> /react.js (built once, reused by every app) *)
    let react = Fennec_buildkit.Esbuild.build ~entry:runtime ~format:"iife" ~minify () in
    write_file (Filename.concat outdir "react.js") react;
    Printf.printf "  runtime %-26s -> react.js\n" (Filename.basename runtime);
    let shim_banner = read_file shim in
    let apps = discover_apps frontend_dir in
    if apps = [] then failwith (Printf.sprintf "no apps found under %s/apps" frontend_dir);
    List.iter
      (fun app ->
        (* JS: esbuild the emitted entry emit/.../apps/<app>/main.js *)
        let suffix = "/" ^ Filename.concat (Filename.concat "apps" app) "main.js" in
        (match find_ending emit_dir suffix [] with
        | entry :: _ ->
          let js =
            Fennec_buildkit.Esbuild.build ~entry ~format:"iife" ~global_name:"App"
              ~external_:[ "react"; "react-dom"; "react/jsx-runtime" ] ~banner:shim_banner ~minify
              ()
          in
          let out = Filename.concat outdir (Printf.sprintf "_apps/%s/main.js" app) in
          mkdir_p (Filename.dirname out);
          write_file out js;
          Printf.printf "  app %-30s -> _apps/%s/main.js\n" app app
        | [] ->
          failwith
            (Printf.sprintf "app %S: no emitted entry (apps/%s/main.js) under %s" app app emit_dir));
        (* CSS: compile <frontend>/apps/<app>/main.scss (path-aware @use) *)
        let scss_src =
          Filename.concat frontend_dir (Printf.sprintf "apps/%s/main.scss" app)
        in
        if Sys.file_exists scss_src then begin
          let css = Fennec_buildkit.Css.scss_path ~minify scss_src in
          let out = Filename.concat outdir (Printf.sprintf "_apps/%s/main.css" app) in
          mkdir_p (Filename.dirname out);
          write_file out css;
          Printf.printf "  app %-30s -> _apps/%s/main.css\n" app app
        end)
      apps;
    (* merge the shared static tree in last (clash with a bundle output is fatal) *)
    (match stage_public ~outdir ~public_dir with
    | Ok () -> Printf.printf "  staged %-27s -> %s/\n" public_dir outdir
    | Error e -> failwith e);
    Ok ()
  with Failure m -> Error m
