(* See contract.mli. The post-release human report + Dockerfile. Pure string-building (primitive args,
   not the pipeline's record types) so it is decoupled and unit-testable. *)

(* This native binary is production BY DEFAULT (Fennec keys dev/prod off bytecode-vs-native, not an env
   var), so the contract is only genuinely deploy-specific values. FENNEC_ENV is listed last, as the
   optional override it now is — there is no mode flag to remember. *)
let env_table =
  [ ( "MONGO_URL",
      "Data backend: burrow://<dir> (embedded, persistent), mongodb://… (real mongod), or :memory: \
       (ephemeral, in-process). Unset → no DB (database features fail when first used)." );
    ("FENNEC_PORT", "Base listen port. Precedence: FENNEC_PORT, else $PORT (PaaS), else 443/80.");
    ("MAIL_URL", "Outbound email transport (an SMTP URL). Unset → emails are logged to stdout.");
    ( "FENNEC_ENV",
      "Optional override — this native binary is already production. Set `development` only to run it \
       in dev mode locally." ) ]

let human_size bytes =
  let b = float_of_int bytes in
  if bytes >= 1024 * 1024 then Printf.sprintf "%.1f MB" (b /. 1024. /. 1024.)
  else if bytes >= 1024 then Printf.sprintf "%.1f KB" (b /. 1024.)
  else Printf.sprintf "%d B" bytes

let render ~path ~bytes ~embedded =
  let assets_line =
    match embedded with
    | Some n -> Printf.sprintf "assets embedded: %d file%s" n (if n = 1 then "" else "s")
    | None -> "no web root (API/SSR-only)"
  in
  let buf = Buffer.create 512 in
  let p fmt = Printf.ksprintf (Buffer.add_string buf) fmt in
  p "\n  released  %s  (%s · native · production · prod-lean · %s)\n\n" path (human_size bytes) assets_line;
  p "  run it (it is production by default — no mode flag needed):\n";
  p "    MONGO_URL=<url> %s\n\n" path;
  p "  runtime environment:\n";
  List.iter (fun (k, desc) -> p "    %-11s  %s\n" k desc) env_table;
  Buffer.contents buf

let dockerfile ~name ~bin =
  (* a Docker COPY source is relative to the build context (the project root), so drop any leading
     "./" the caller passed (e.g. an outdir of "./dist") — keeping the orchestrator free of path cosmetics *)
  let bin = if String.length bin >= 2 && String.sub bin 0 2 = "./" then String.sub bin 2 (String.length bin - 2) else bin in
  Printf.sprintf
    {|# Generated by `fennec release --docker`. A RUNTIME image — it copies the pre-built binary.
#
# IMPORTANT: the binary is built for the OS/arch `fennec release` ran on. For a Linux container, run
# `fennec release` on Linux (e.g. in CI) — a macOS binary will not run here. The burrow:// (embedded)
# backend is self-contained; a real mongodb:// backend needs the MongoDB C driver in the image.

FROM debian:stable-slim
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY %s /app/%s

# The native binary is production by default — no FENNEC_ENV needed.
ENV FENNEC_PORT=8080
EXPOSE 8080

# Provide the data backend at run time, e.g.  -e MONGO_URL=burrow:///app/data
CMD ["/app/%s"]
|}
    bin name name

(* ──── tests ──── *)

let%test "human_size renders MB" = human_size (44 * 1024 * 1024) = "44.0 MB"
let%test "human_size renders KB" = human_size 9728 = "9.5 KB"
let%test "human_size renders bytes" = human_size 512 = "512 B"

let%test "the run line needs no mode flag — production by default" =
  let s = render ~path:"./dist/server" ~bytes:1000 ~embedded:(Some 3) in
  (not (Fennec_hunt_unit.str_contains s "FENNEC_ENV=production"))
  && Fennec_hunt_unit.str_contains s "MONGO_URL=<url> ./dist/server"

let%test "the embed count is pluralised, API-only is labelled" =
  Fennec_hunt_unit.str_contains (render ~path:"p" ~bytes:1 ~embedded:(Some 1)) "1 file)"
  && Fennec_hunt_unit.str_contains (render ~path:"p" ~bytes:1 ~embedded:None) "API/SSR-only"

let%test "the Dockerfile copies the staged binary; sets no mode directive (prod by default)" =
  let d = dockerfile ~name:"server" ~bin:"dist/server" in
  Fennec_hunt_unit.str_contains d "COPY dist/server /app/server"
  && (not (Fennec_hunt_unit.str_contains d "ENV FENNEC_ENV"))
  && Fennec_hunt_unit.str_contains d {|CMD ["/app/server"]|}

let%test "the Dockerfile COPY path drops a leading ./ from the outdir" =
  Fennec_hunt_unit.str_contains (dockerfile ~name:"server" ~bin:"./dist/server") "COPY dist/server /app/server"
