(* See cross.mli. The Docker-backed cross-build engine: parse targets, generate the multi-stage build
   Dockerfile, and construct the buildx command. The heavy lifting happens inside the container (a native
   build for the target platform), so this module stays pure string/command construction — fully
   unit-testable, and the slow part is Docker's, run by the orchestrator. *)

type platform = {
  os : string;
  arch : string;
}

let slug p = p.os ^ "-" ^ p.arch
let docker_platform p = p.os ^ "/" ^ p.arch

type output =
  | To_dir of string
  | To_image of string

let default_base = "ocaml/opam:debian-12-ocaml-5.4"

(* ── target parsing ─────────────────────────────────────────────────────────────────────────────── *)

let supported_arches = [ "amd64"; "arm64" ]

let parse_one (raw : string) : (platform, string) result =
  let s = String.trim raw in
  match String.split_on_char '/' s with
  | [ os; arch ] -> (
    let os = String.lowercase_ascii os and arch = String.lowercase_ascii arch in
    match os with
    | "darwin" | "macos" ->
      Error
        (Printf.sprintf
           "target %S: Docker cannot build macOS binaries (there are no macOS containers). Build on a \
            Mac (`fennec release` already makes the host's macOS binary), or use a macOS CI runner — see \
            README.md."
           s)
    | "windows" ->
      Error (Printf.sprintf "target %S: Docker cannot build Windows binaries here — use a Windows CI runner (see README.md)." s)
    | "linux" ->
      if List.mem arch supported_arches then Ok { os; arch }
      else Error (Printf.sprintf "target %S: unsupported arch %S (supported: %s)." s arch (String.concat ", " supported_arches))
    | _ -> Error (Printf.sprintf "target %S: only linux/<arch> is buildable via Docker." s))
  | _ -> Error (Printf.sprintf "target %S: expected the form os/arch, e.g. linux/amd64." s)

let parse_targets (specs : string list) : (platform list, string) result =
  let raw = List.concat_map (String.split_on_char ',') specs |> List.map String.trim |> List.filter (fun s -> s <> "") in
  let rec go acc = function
    | [] -> Ok (List.rev acc)
    | s :: rest -> ( match parse_one s with Error _ as e -> e | Ok p -> if List.mem p acc then go acc rest else go (p :: acc) rest)
  in
  go [] raw

let docker_available () : (unit, string) result =
  if Sys.command "docker buildx version >/dev/null 2>&1" = 0 then Ok ()
  else
    Error
      "docker (with buildx) is required for --target cross-builds. Install Docker Desktop (or the docker \
       buildx plugin) and retry; or run `fennec release` without --target to build for this host."

(* ── the generated multi-stage build Dockerfile ─────────────────────────────────────────────────── *)

let final_stage ~exe_target ~name = function
  | To_dir _ ->
    (* a scratch stage holding ONLY the binary, so `--output type=local` writes just it to ./dist *)
    Printf.sprintf "FROM scratch AS export\nCOPY --from=build /home/opam/app/_build/default/%s /%s\n" exe_target name
  | To_image _ ->
    Printf.sprintf
      {|FROM debian:stable-slim AS runtime
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /home/opam/app/_build/default/%s /app/%s
ENV FENNEC_PORT=8080
EXPOSE 8080
CMD ["/app/%s"]
|}
      exe_target name name

let build_dockerfile ~base ~exe_target ~name ~output =
  let what = match output with To_dir _ -> "extracts the stripped binary to ./dist" | To_image _ -> "produces a slim runtime image" in
  Printf.sprintf
    {|# syntax=docker/dockerfile:1
# Generated by `fennec release --target …`. Builds the app NATIVELY inside a target-platform container
# (no host cross-toolchain — OCaml + C stubs make true cross-compilation the hard path; building in the
# target image is the robust one, à la cross-rs) and %s.
#
# The first build is slow: it installs the toolchain (OCaml + Go + Rust) and compiles every dependency.
# buildx caches the layers, so repeat builds are fast — and `--build-image <img>` can point at a
# pre-baked image (see fennec-build.Dockerfile / README.md) to skip the toolchain install entirely.
FROM %s AS build
USER root
# fennec's native system deps (libmongoc for the mongo FFI) + the Go and Rust toolchains the `fennec`
# CLI's bundlers (esbuild / CSS) need. Tune the apt set to your app's own depexts.
RUN apt-get update \
 && apt-get install -y --no-install-recommends pkg-config libssl-dev libmongoc-dev ca-certificates curl xz-utils \
 && rm -rf /var/lib/apt/lists/*
ARG TARGETARCH
RUN curl -fsSL "https://go.dev/dl/go1.24.0.linux-${TARGETARCH}.tar.gz" | tar -C /usr/local -xz
USER opam
RUN curl --proto '=https' --tlsv1.2 -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
ENV PATH="/usr/local/go/bin:/home/opam/.cargo/bin:${PATH}"
WORKDIR /home/opam/app
COPY --chown=opam:opam . .
# external deps (and, for a downstream app, fennec itself — `opam pin` it first if it is not on your
# opam repository).
RUN opam install . --deps-only --yes
RUN opam exec -- dune build --profile release %s
RUN strip _build/default/%s 2>/dev/null || true
%s|}
    what base exe_target exe_target (final_stage ~exe_target ~name output)

(* ── the buildx command ─────────────────────────────────────────────────────────────────────────── *)

let buildx_command ~platform ~dockerfile ~context ~output =
  let out =
    match output with
    | To_dir dir -> Printf.sprintf "--target export --output type=local,dest=%s" (Filename.quote dir)
    | To_image tag -> Printf.sprintf "--target runtime --tag %s --load" (Filename.quote tag)
  in
  Printf.sprintf "docker buildx build --platform %s -f %s %s %s" (docker_platform platform) (Filename.quote dockerfile) out
    (Filename.quote context)

(* ── tests ──────────────────────────────────────────────────────────────────────────────────────── *)

let%test "parse linux/amd64" = parse_targets [ "linux/amd64" ] = Ok [ { os = "linux"; arch = "amd64" } ]

let%test "comma-separated parses + dedups, order preserved" =
  parse_targets [ "linux/amd64,linux/arm64,linux/amd64" ] = Ok [ { os = "linux"; arch = "amd64" }; { os = "linux"; arch = "arm64" } ]

let%test "darwin is rejected with macOS guidance" =
  match parse_targets [ "darwin/arm64" ] with Error m -> Fennec_hunt_unit.str_contains m "macOS" | Ok _ -> false

let%test "windows is rejected" = (match parse_targets [ "windows/amd64" ] with Error _ -> true | Ok _ -> false)

let%test "an unsupported arch is rejected, naming the supported set" =
  match parse_targets [ "linux/riscv64" ] with Error m -> Fennec_hunt_unit.str_contains m "arch" | Ok _ -> false

let%test "a malformed target is rejected" = (match parse_targets [ "linux" ] with Error _ -> true | Ok _ -> false)

let%test "slug + docker_platform forms" =
  let p = { os = "linux"; arch = "amd64" } in
  slug p = "linux-amd64" && docker_platform p = "linux/amd64"

let%test "build_dockerfile (binary): build + export stages, the release target, the binary copy" =
  let d = build_dockerfile ~base:default_base ~exe_target:"app/server.exe" ~name:"server" ~output:(To_dir "dist/linux-amd64") in
  Fennec_hunt_unit.str_contains d "AS build"
  && Fennec_hunt_unit.str_contains d "FROM scratch AS export"
  && Fennec_hunt_unit.str_contains d "dune build --profile release app/server.exe"
  && Fennec_hunt_unit.str_contains d "COPY --from=build /home/opam/app/_build/default/app/server.exe /server"

let%test "build_dockerfile (image): a runtime stage + CMD" =
  let d = build_dockerfile ~base:default_base ~exe_target:"a/s.exe" ~name:"s" ~output:(To_image "myapp:1") in
  Fennec_hunt_unit.str_contains d "AS runtime" && Fennec_hunt_unit.str_contains d {|CMD ["/app/s"]|}

let%test "buildx_command (binary): platform, export target, local output" =
  let c = buildx_command ~platform:{ os = "linux"; arch = "amd64" } ~dockerfile:"/tmp/D" ~context:"." ~output:(To_dir "dist/x") in
  Fennec_hunt_unit.str_contains c "--platform linux/amd64"
  && Fennec_hunt_unit.str_contains c "--target export"
  && Fennec_hunt_unit.str_contains c "type=local"

let%test "buildx_command (image): runtime target, tag, load" =
  let c = buildx_command ~platform:{ os = "linux"; arch = "arm64" } ~dockerfile:"/tmp/D" ~context:"." ~output:(To_image "app:1") in
  Fennec_hunt_unit.str_contains c "--target runtime" && Fennec_hunt_unit.str_contains c "--tag" && Fennec_hunt_unit.str_contains c "--load"
