(* See verify.mli. Classify the build's assets.ml as the real embed, the dev stub, or absent.

   We read the generated module's TEXT rather than try to execute it: the real embed (from `fennec
   build --embed`, see cli/webroot.ml) opens with `let assets : (string * string) list = [`, while the
   dev stub is just `let lookup _ = None`. The file count is read from the assembled web-root dir on
   disk (the source of truth), not parsed out of the module. *)

type assets =
  | Embedded of int
  | Stub
  | No_webroot

(* substring test, shared shape with Lean.contains; kept local so each module stays self-contained *)
let contains hay ndl =
  let hl = String.length hay and nl = String.length ndl in
  if nl = 0 then true
  else begin
    let rec matches i j = j = nl || (hay.[i + j] = ndl.[j] && matches i (j + 1)) in
    let rec scan i = i + nl <= hl && (matches i 0 || scan (i + 1)) in
    scan 0
  end

let is_embed_source (text : string) : bool = contains text "let assets : (string * string) list"

let read_file path = In_channel.with_open_bin path In_channel.input_all

(* count regular files under [dir], recursively (the web root is small; this is for the report) *)
let rec count_files dir =
  match Sys.readdir dir with
  | exception _ -> 0
  | entries ->
    Array.fold_left
      (fun acc name ->
        let p = Filename.concat dir name in
        if (try Sys.is_directory p with _ -> false) then acc + count_files p else acc + 1)
      0 entries

let assets (t : Target.t) : assets =
  if not (Sys.file_exists t.Target.assets_ml) then No_webroot
  else
    match read_file t.Target.assets_ml with
    | exception _ -> No_webroot
    | text -> if is_embed_source text then Embedded (count_files t.Target.webroot) else Stub

(* ──── tests ──── *)

let%test "the dev stub is not an embed" = not (is_embed_source "let lookup (_ : string) : string option = None\n")

let%test "the real embed module is an embed" =
  is_embed_source "(* generated by `fennec build --embed` *)\nlet assets : (string * string) list = [\n  (\"a\", \"b\");\n]\n"

let%test "an empty module is not an embed" = not (is_embed_source "")
