(** Verify that a release build actually baked its web root into the binary — catching the silent
    failure where the artifact compiles fine but serves nothing.

    The build emits [assets.ml] in one of two shapes: the dev {e stub} ([let lookup _ = None]) or the
    real embed ([let assets : (string * string) list = [ … ]], generated by [fennec build --embed]).
    A release that produced the stub means the embed rule never ran — the binary will 404 its assets.
    An app with no web root at all (an API/SSR-only server) emits no [assets.ml]; that is fine. *)

(** The embed status of a built deployable. *)
type assets =
  | Embedded of int  (** the real embed module, with this many files in the assembled web root *)
  | Stub  (** [assets.ml] is the dev stub — the release embed rule did not run (a misconfiguration) *)
  | No_webroot  (** no [assets.ml] at all — an API/SSR-only server with nothing to embed (fine) *)

(** [is_embed_source text] is [true] when [text] is the real embed module, [false] for the dev stub —
    the pure, testable core of {!assets}. *)
val is_embed_source : string -> bool

(** [assets t] classifies the built [t] by reading its generated [assets.ml] and counting the web
    root. Best-effort: an unreadable [assets.ml] is treated as {!No_webroot}. *)
val assets : Target.t -> assets
