(* See verify.mli. Classify the build's assets.ml as the real embed, the dev stub, or absent.

   We read the generated module's TEXT rather than try to execute it: the real embed (from `fennec
   build --embed`, see cli/webroot.ml) opens with `let assets : (string * string) list = [`, while the
   dev stub is just `let lookup _ = None`. The file count is read from the assembled web-root dir on
   disk (the source of truth), not parsed out of the module. *)

type assets =
  | Embedded of int
  | Stub
  | No_webroot

(* The byte-exact opening line the real embed module carries — [cli/webroot.ml]'s `--embed` emitter
   prints it verbatim (the dev stub is just `let lookup _ = None`). A test below pins this literal so a
   reformat over there breaks here loudly instead of silently classifying every release as a Stub.
   [Fennec_hunt_unit.str_contains] is the shared allocation-free substring search. *)
let embed_marker = "let assets : (string * string) list"

let is_embed_source (text : string) : bool = Fennec_hunt_unit.str_contains text embed_marker

let assets (t : Target.t) : assets =
  if not (Sys.file_exists t.Target.assets_ml) then No_webroot
  else
    match Util.read_file t.Target.assets_ml with
    | exception _ -> No_webroot
    | text -> if is_embed_source text then Embedded (Util.count_files t.Target.webroot) else Stub

(* ──── tests ──── *)

let%test "the dev stub is not an embed" = not (is_embed_source "let lookup (_ : string) : string option = None\n")

let%test "the real embed module is an embed" =
  is_embed_source "(* generated by `fennec build --embed` *)\nlet assets : (string * string) list = [\n  (\"a\", \"b\");\n]\n"

let%test "an empty module is not an embed" = not (is_embed_source "")

(* guards the literal coupling to cli/webroot.ml's `--embed` emitter: if its first emitted line is ever
   reformatted, this breaks loudly here instead of every release silently failing the embed gate. *)
let%test "is_embed_source matches the byte-exact opening line cli/webroot.ml --embed emits" =
  is_embed_source "let assets : (string * string) list = [\n"
