(* PWA support, framework-owned. ONE declaration per app yields the three artifacts a PWA needs:
   - the web app manifest (generated JSON, served at <scope>manifest.webmanifest),
   - the service worker (generated JS, served at <scope>sw.js with Service-Worker-Allowed),
   - the head snippet (<link rel=manifest> + theme color + the registration script).

   The framework owns the asset graph, so the SW's precache list and cache VERSION are exact: the
   version is a digest of the precached assets' contents, the cache name embeds it, and activation
   deletes every older cache — an atomic swap per deploy, no stale-mix bugs. The fetch strategy is
   deliberate for an SSR framework:
   - precached assets (bundles/css/icons): cache-first (immutable per version);
   - navigations: network-first (SSR freshness online), falling back OFFLINE to the last runtime-
     cached copy of that page — and because fennec's SSR pages EMBED their data seed, an offline
     boot of a visited route restores not just the shell but the page's data, through the same
     seed → tentative → quiesce path hydration always uses;
   - everything else passes through (and falls back to a cache match offline).

   Updates: the SW installs and WAITS (no silent skipWaiting — a mid-session swap could mix bundle
   versions); the registration script surfaces a `fennec:sw-update` window event (Pwa_client wraps it
   as a Fur signal) and exposes window.__fennecApplyUpdate, which messages SKIP_WAITING and reloads
   on controllerchange — the user-confirmed update flow. *)

(* ---- config ---------------------------------------------------------------- *)

type icon = { src : string; sizes : string; mime : string }

type t = {
  name : string;
  short_name : string;
  scope : string; (* the app's mount path, normalized to end with "/" — also the manifest scope *)
  start_url : string;
  display : string;
  theme_color : string;
  background_color : string;
  icons : icon list;
}

let icon ?(mime = "image/png") ~sizes src = { src; sizes; mime }

let v ?short_name ?(scope = "/") ?start_url ?(display = "standalone") ?(theme_color = "#111111")
    ?(background_color = "#ffffff") ~icons name =
  let scope = if String.length scope > 0 && scope.[String.length scope - 1] = '/' then scope else scope ^ "/" in
  {
    name;
    short_name = Option.value short_name ~default:name;
    scope;
    start_url = Option.value start_url ~default:scope;
    display;
    theme_color;
    background_color;
    icons;
  }

(* ---- tiny JSON emission (manifest-sized; no dependency on the DDP json layer) ---- *)

let json_str s =
  let b = Buffer.create (String.length s + 2) in
  Buffer.add_char b '"';
  String.iter
    (fun c ->
      match c with
      | '"' -> Buffer.add_string b "\\\""
      | '\\' -> Buffer.add_string b "\\\\"
      | '\n' -> Buffer.add_string b "\\n"
      | c when Char.code c < 0x20 -> Buffer.add_string b (Printf.sprintf "\\u%04x" (Char.code c))
      | c -> Buffer.add_char b c)
    s;
  Buffer.add_char b '"';
  Buffer.contents b

(* ---- the manifest ---------------------------------------------------------- *)

let manifest (cfg : t) : string =
  let icon_json i =
    Printf.sprintf {|{"src":%s,"sizes":%s,"type":%s}|} (json_str i.src) (json_str i.sizes) (json_str i.mime)
  in
  Printf.sprintf
    {|{"name":%s,"short_name":%s,"scope":%s,"start_url":%s,"display":%s,"theme_color":%s,"background_color":%s,"icons":[%s]}|}
    (json_str cfg.name) (json_str cfg.short_name) (json_str cfg.scope) (json_str cfg.start_url)
    (json_str cfg.display) (json_str cfg.theme_color) (json_str cfg.background_color)
    (String.concat "," (List.map icon_json cfg.icons))

(* ---- the service worker ----------------------------------------------------- *)

let js_str_array urls = String.concat "," (List.map json_str urls)

let service_worker (cfg : t) ~(version : string) ~(precache : string list) : string =
  Printf.sprintf
    {|/* generated by fennec.pwa — do not edit (the precache list and version come from the build) */
const CACHE = %s;
const PRECACHE = [%s];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k.startsWith(%s) && k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});
self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    /* network-first: SSR freshness online; offline falls back to the last seen copy of the page
       (whose embedded seed restores its data), then to the start page */
    e.respondWith(
      fetch(req)
        .then((resp) => {
          const copy = resp.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return resp;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match(%s)))
    );
    return;
  }
  /* assets: cache-first (precached entries are immutable per version), network otherwise,
     cache-match as the offline fallback */
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req).catch(() => caches.match(req))));
});
|}
    (json_str (Printf.sprintf "fennec-%s-%s" cfg.short_name version))
    (js_str_array precache)
    (json_str (Printf.sprintf "fennec-%s-" cfg.short_name))
    (json_str cfg.start_url)

(* ---- the head snippet (manifest link + theme + registration) ----------------- *)

let head_html (cfg : t) : string =
  Printf.sprintf
    {|<link rel="manifest" href="%smanifest.webmanifest"><meta name="theme-color" content="%s"><meta name="fennec-persist" content="%s"><script>
if ('serviceWorker' in navigator) navigator.serviceWorker.register('%ssw.js', {scope: '%s'}).then((reg) => {
  window.__fennecApplyUpdate = () => {
    if (reg.waiting) {
      navigator.serviceWorker.addEventListener('controllerchange', () => location.reload());
      reg.waiting.postMessage({type: 'SKIP_WAITING'});
    }
  };
  const announce = () => window.dispatchEvent(new CustomEvent('fennec:sw-update'));
  if (reg.waiting && navigator.serviceWorker.controller) announce();
  reg.addEventListener('updatefound', () => {
    const w = reg.installing;
    if (w) w.addEventListener('statechange', () => {
      if (w.state === 'installed' && navigator.serviceWorker.controller) announce();
    });
  });
});
</script>|}
    cfg.scope cfg.theme_color cfg.short_name cfg.scope cfg.scope

(* ---- the serving paw --------------------------------------------------------- *)

(* the version: a digest over the precached assets' CONTENTS (via the same [assets] lookup the
   static paw serves from), so a redeploy with any changed asset rolls the cache atomically *)
let version_of ~(assets : string -> string option) (precache : string list) : string =
  let buf = Buffer.create 1024 in
  List.iter
    (fun url ->
      Buffer.add_string buf url;
      match assets url with Some body -> Buffer.add_string buf (Digest.to_hex (Digest.string body)) | None -> ())
    precache;
  String.sub (Digest.to_hex (Digest.string (Buffer.contents buf))) 0 12

let paw (cfg : t) ~(assets : string -> string option) ~(precache : string list) : Fennec_paw.Paw.t =
  let version = version_of ~assets precache in
  let manifest_body = manifest cfg in
  let sw_body = service_worker cfg ~version ~precache in
  let manifest_path = cfg.scope ^ "manifest.webmanifest" in
  let sw_path = cfg.scope ^ "sw.js" in
  fun c ->
    let open Fennec_paw in
    if Conn.meth c <> Fennec_core.Http.GET then c
    else
      match Conn.path c with
      | p when p = manifest_path ->
          Conn.text c manifest_body
            ~headers:[ ("Content-Type", "application/manifest+json"); ("Cache-Control", "no-cache") ]
      | p when p = sw_path ->
          (* Service-Worker-Allowed lets the worker claim the whole app scope even when the script
             URL sits inside it; no-cache so a new deploy's SW is picked up promptly *)
          Conn.text c sw_body
            ~headers:
              [ ("Content-Type", "text/javascript"); ("Service-Worker-Allowed", cfg.scope);
                ("Cache-Control", "no-cache") ]
      | _ -> c
