let render () =
  String.concat "\n"
    [ "# Fennec";
      "";
      "Fennec is an OCaml fullstack framework built on plain dune projects. Use the CLI as the source of truth for builds, dev feedback, tests, docs, and agent fastlane feedback.";
      "";
      "## Start Here";
      "";
      "```sh";
      "fennec                 # print this guide";
      "fennec dev             # discover and run the app with live reload";
      "fennec test            # fast unit gate";
      "fennec test all        # unit -> http -> browser -> system -> docs";
      "fennec test docs       # doc coverage, warn-only by default";
      "fennec build INPUT...  # native JS/CSS/SCSS bundling";
      "```";
      "";
      "The project remains a normal dune project. `fennec` adds restart/livereload, native asset bundling, app test orchestration, doc coverage, and agent-facing feedback.";
      "";
      "## Dev Loop";
      "";
      "Run:";
      "";
      "```sh";
      "fennec dev";
      "```";
      "";
      "With no server path, Fennec asks dune for the executable that calls `Fennec.serve`. Dune remains the sole source watcher and builder. Backend changes restart the server; frontend changes reload or hot-swap CSS; build failures keep the last good server serving when possible.";
      "";
      "Useful variants:";
      "";
      "```sh";
      "fennec dev --dry-run";
      "fennec dev --port 9000";
      "fennec dev --mongo";
      "fennec dev --clean";
      "```";
      "";
      "## Agent Fastlane";
      "";
      "For coding agents, use the hook fastlane. Do not run manual `dune build` / `dune runtest` probes after every edit.";
      "";
      "Start one dev loop with an agent journal and ask Fennec to attach the current harness:";
      "";
      "```sh";
      "fennec dev --agent --attach --port 9123";
      "```";
      "";
      "Attach installs one guarded user-level post-tool hook when the active harness supports it. The hook command is:";
      "";
      "```sh";
      "fennec agent hook --timeout 12";
      "```";
      "";
      "After attach, edit normally. The first edit that reaches the hook injects model context containing `Fennec dev feedback after this tool`. Do not compensate by tailing logs or running build/test probes after every edit.";
      "";
      "The hook is stateful: it returns the next undelivered Fennec verdict, including feedback that settled before the hook process started. Do not call separate wait commands after edits. Do not parse terminal output.";
      "";
      "The agent verdict includes served change, inline-test result when tests ran, inferred affected surface, timing fields, and focused compiler diagnostics with file/line/code frame when a build fails.";
      "";
      "Recovery:";
      "";
      "```sh";
      "fennec agent status";
      "```";
      "";
      "`status` reports the journal, latest verdict, configured port, and whether the recorded devserver pid is alive.";
      "";
      "## Tests";
      "";
      "```sh";
      "fennec test              # unit";
      "fennec test http";
      "fennec test browser";
      "fennec test system";
      "fennec test docs --strict";
      "fennec test new system NAME";
      "```";
      "";
      "Use the narrowest cut that proves the change. `all` is the full local confidence pass.";
      "";
      "## Agent Rules";
      "";
      "- Prefer `fennec dev --agent --attach` for iterative coding; it installs the guarded post-tool hook for the active harness.";
      "- Trust hook verdicts for compile/test/reload feedback; they are generated by the devserver, not by terminal scraping.";
      "- Treat attach as live after an edit produces `Fennec dev feedback after this tool` in your model context.";
      "- On build failure, fix the reported focused diagnostic first.";
      "- Do not run explicit wait commands as the normal loop; use `fennec agent status` only for recovery.";
      "- Avoid adding local harness config or root instruction files unless the user explicitly asks.";
      "- Before final handoff, run the relevant `fennec test ...` cut or explain why it was not run.";
      "" ]

let%test "guide names the agent hook" =
  Fennec_hunt_unit.str_contains (render ()) "fennec agent hook --timeout 12"

let%test "guide names attach path" =
  Fennec_hunt_unit.str_contains (render ()) "fennec dev --agent --attach --port 9123"

let%test "guide tells agents not to poll builds after hooks" =
  Fennec_hunt_unit.str_contains (render ()) "Do not run manual `dune build` / `dune runtest` probes after every edit"

let%test "guide makes hook the only normal fastlane path" =
  Fennec_hunt_unit.str_contains (render ()) "Fennec dev feedback after this tool"
  && Fennec_hunt_unit.str_contains (render ()) "Do not run explicit wait commands"
  && not (Fennec_hunt_unit.str_contains (render ()) "fennec agent wait --after")
